# Generated by Django 3.2.5 on 2021-08-09 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loot_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticLootHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot_tracker.staticmember')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot_tracker.item')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot_tracker.patch')),
            ],
        ),
    ]
